adds new branch
dandelionadia/example pull request #2
Opened 2018-12-10 10:09 UTC by dandelionadia

2018-12-13 15:24 UTC, kettanaito requested changes

2018-12-13 15:24 UTC, kettanaito commented on src/styles/base/support.scss
> +    margin: 0;
Indentation.

2018-12-13 15:24 UTC, kettanaito commented on src/styles/base/support.scss
> +    margin: 0;
Indentation.

2018-12-13 15:24 UTC, kettanaito commented on src/styles/base/support.scss
> +                transform: translateY(-20px);
You have this `20px` repeating often, so you can put it into a variable on top of this file.

```scss
$item-height: 20px;
```

And then reuse it, so if you want to change it, you change it in one place.

2018-12-13 15:24 UTC, kettanaito commented on src/templates/atoms/card.nunj
> +
I think you don't need this empty line. Remove?

2018-12-13 15:24 UTC, kettanaito commented on src/templates/atoms/card.nunj
> +    <img src="{{logo}}" class="serve__logo"></img>
Image tag is self-closing: `<img />`

2018-12-13 15:24 UTC, kettanaito commented on src/templates/atoms/card.nunj
> +        <div>{{avtor}}</div>
```diff
- avtor
+ author
```

2018-12-13 15:26 UTC, dandelionadia commented on src/templates/atoms/card.nunj
> +        <div>{{avtor}}</div>
:D

2018-12-13 15:32 UTC, dandelionadia commented on src/templates/atoms/card.nunj
> +    <img src="{{logo}}" class="serve__logo"></img>
I do not know how it happened :)

2018-12-21 10:26 UTC, kettanaito requested changes

2018-12-21 10:26 UTC, kettanaito commented on src/templates/pages/index.nunj
> +             Are you a driven and motivated 1st Line IT Support Engineer?
Please don't put plain text ("Foo"), and HTML elements "<a>" next to each other.

```diff
- <a>Text</a>
- Lorem ipsum
+ <a>Text</a>
+ <p>Lorem ipsum</p>
```

You can also use `<span>` instead of a paragraph.

2019-01-05 11:07 UTC, kettanaito approved these changes

2019-01-05 11:07 UTC, kettanaito commented on src/templates/components/header.nunj
> +              <div class="cont">
`cont` class means nothing. Please come up with a more descriptive class name.

2019-01-05 11:07 UTC, kettanaito commented on src/templates/components/header.nunj
> +                          <a href="#">{{item.title}}</a>
Maybe add each item a url?
So you could do:

```nunj
<a href={{item.url}}>{{item.title}}</a>
```

2019-01-05 12:37 UTC, kettanaito approved these changes

2019-01-05 12:38 UTC, merged